### ISSUE TITLE
AI2Thor docker build failure

### ISSUE THREAD

**Issue by Ram81** [allenai/ai2thor-docker#13]
Hi,

When running the `./scripts/build.sh` command I am running into the following issue - 

```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is re
commended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'ai2thor.build' has no attribute 'DEFAULT_CLOUDRENDERING_COMMIT_ID'
The command '/bin/sh -c pip3 install -r requirements.txt && python3 -c "import os; import ai2thor.build; ai2thor.build.Build('CloudRendering
', ai2thor.build.DEFAULT_CLOUDRENDERING_COMMIT_ID, False, releases_dir=os.path.join(os.path.expanduser('~'), '.ai2thor/releases')).download(
)"' returned a non-zero code: 1
```

Can someone help with the above issue? or point us to a stable build that we can use?

**Comment by knightpegasus7382** [comment]
Hey,

Changing the ai2thor version in `./requirements.txt` to an earlier version fixed this issue for me. I changed the contents of `./requirements.txt` from:

`ai2thor`

to 

`ai2thor==4.0.0`

The latest version(s?) of ai2thor seems to be incompatible with the current state of ai2thor-docker.
