### ISSUE TITLE
module-init-tools replaced by kmod

### ISSUE THREAD

**Issue by cedorman** [allenai/ai2thor-docker#5]
module-init-tools has been replaced by kmod, a drop in replacement.  This actually happened years ago, but the older module-init-tools has been supported for the last couple of versions of Ubuntu (see: https://packages.ubuntu.com/search?keywords=module-init-tools) .  However, it is not there for 20.04, so the apt-get install for it fails in the Dockerfile.

**Comment by ekolve** [comment]
Fixed
